### ISSUE TITLE
Blog index layout

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/docs#124]
## Expected Behaviour

I can see a list of all blog posts that have been published along with their publish data

## Current Behaviour

The blog page shows all the posts but as full pages rather than summaries. This makes it hard to see what blogs are available and requires you to scroll through a lot of pages before they come up

## Possible Solution

This could be a bug where we need to include a summary point in the posts to reduce the size of each blog in the main page ( https://docs.hamlet.io/blog ) or we need to add a page with summary, title and publish date

## Context

The main context here is to make sure our blog posts are visible and discoverable by users

**Comment by RossMurr4y** [comment]
Yep, agreed. I had always thought that the single-page stream was the only way to organise the blog posts but it looks like that behaviour is just the default if you do not specify a truncated description for the article.

https://docusaurus.io/docs/2.0.0-alpha.75/blog#summary-truncation

**Comment by roleyfoley** [comment]
Looks like you can show a full listing of the docs on the main page instead of the last 5.
