### ISSUE TITLE
Fix - Reference Data

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#14]
Currently the Reference data for components is still in a state that was to display the design of the docs site. The formatting for all components needs to be updated on the "Attribute Reference" tab. Currently it is formatted to display hyperlinks to old content. The hyperlinks need to be removed and a more easily read format provided - perhaps a markdown table.

**Comment by roleyfoley** [comment]
Should we look at generating the reference data in JSON schema from the engine itself. We could then render the schema using a react component specific for the documentation

**Comment by roleyfoley** [comment]
Similar to this article from cloudflare 
https://blog.cloudflare.com/cloudflares-json-powered-documentation-generator/

**Comment by RossMurr4y** [comment]
I like that idea. It'll mean a bit of fiddling because the reference data will now no longer be in markdown, so it'll need to be converted from a Docs .md file to a Pages .js react file - but I don't see any reason we couldn't do that easily enough. Once its setup then its done so that'll be nice.

**Comment by RossMurr4y** [comment]
Closing ticket as has been superceded by hamlet-io/docs#15
