### ISSUE TITLE
Feature - React Page to display Reference Data.

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#15]
**Feature Description**

As the place with the greatest potential for confusion when first getting started with hamlet, the reference data documentation for hamlet components that can defined in a users CMDB should be as clear and understandable as possible. The more assistance we can offer a user in identifying the correct design of their desired component the better.

Within hamlet itself, each component is defined and verified by its own schema. This schema is soon to be converted into [JSON schema format](https://json-schema.org/) and the build process of hamlet will be updated to publish a copy of each resources JSON schema into this docs repository. It is from those jsonschema definitions that our Component Reference docs should be defined, so as to ensure that the documentation is always in alignment with the product.

**Feature Definition**

In order to accomplish this a new docusaurus [Page](https://v2.docusaurus.io/docs/creating-pages/#adding-a-new-page) should be created, that renders the content of the JSONSchema files into a human-readable format. This will require a new React component for `HamletReferences` that should import all JSON Schema files in a given directory (also required to be defined), then return all of them in the desired manner.

For each component schema discovered, the output should look as follows:

1. Component heading.
2. Component description.
3. Any sub-components that are defined with corresponding definitions.
4. A 4+-tabbed [multi-language code block](https://v2.docusaurus.io/docs/markdown-features/#multi-language-support-code-blocks) Component with code tabs defined below.
5. Attribute Reference for attributes, sub-attributes etc. within the Schema. This should be below the multi-language code block, so as the user can read attribute definitions and review their chosen tab of the Schema at-will. These should also be expandable options so as to be able to review the desired attribute and its location on the Schema simultaneously on an average computer monitor.

Any new React components required for this implementation should live under `/src/components` so as to keep the `/src/pages/` directory tidy.

**Code Tabs**
- Schema - JSON Format - codeblock that shows the outline of the component schema. These should look the same as the codeblocks already displayed on our [existing reference page](https://hamlet.io/docs/reference/component-reference).
- Schema - YAML Format - this should be the same as the previous tab, except defined in YAML. The YAML will not be defined within the schema, it should be translated on the fly by additional means.
- Designer - splitting the tab into two vertically, the left-hand side should offer text-fields to the user for each Attribute, and the right hand side should display the schema-conforming object. The output should be swap-able between JSON and YAML at will.
- Examples - The JSON Schema will define one or greater examples, and for each example there should be an additional tab showing this example in a code block. This will allow us to offer simple and complex examples as required per component.

All of these tabs should include a click-to-copy feature. This is an out-of-the-box feature of the existing multi-language code block tabs, however should something else end up being used this feature should remain.

Though this new page will be a docusaurus "Page" (a React page), it should appear to users to be a part of our "Docs" section. As such it will need to be referenced using a Link in `sidebar.js` i.e:

```
{
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'CMDB',
          items: [
            'reference/cmdb/cmdb-folder-structure-01',
            'reference/cmdb/cmdb-folder-structure-02'
          ]
        },
        {
          type: 'link',
          label: 'Component Ref',
          href: '../../../components'
        },
        'reference/glossary',
      ]
}
```

**Schema Structure**
Currently the Schema export from hamlet is still being implemented, however development on this can proceed based on the following Schema structure. 

[Deployed preproduction schema](https://hamlet-docs-git-add-schema-documents.hamlet.now.sh/schema/latest/blueprint/component.json)
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://hamlet.io/schema/latest/blueprint/component.json",

    "definitions": {

      "deployment-units" : {
        "type" : "array",
        "items" : {
          "type" : "string"
        }
      },

      "instances" : {
        "type" : "object",
        "additionalProperties": true,
        "properties": {
          "Versions" : {
            "type" : "object",
            "additionalProperties": true
          }
        }
      },

      "s3": {
        "type": "object",
        "properties": {
          "Instances" : { "$ref": "#/definitions/instances" },
          "DeploymentUnits" : { "$ref" : "#/definitions/deployment-units" },
          "Lifecycle": {
            "type": "object",
            "additionalProperties" : false,
            "properties": {
              "Expiration" : {
                "description": "Provide either a date or a number of days",
                "type" : [ "string", "number" ]
              },
              "Offline" : {
                "description" : "Provide either a date or a number of days",
                "type" : [ "string", "number" ]
              },
              "Versioning" : {
                "type" : "boolean",
                "default" : false
              }
            }
          },
          "Website" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties": {
              "Index" : {
                "type" : "string",
                "default" : "index.html"
              },
              "Error" : {
                "type" : "string",
                "default" : ""
              }
            }
          },
          "PublicAccess" : {
            "type" : "object",
            "patternProperties": {
              "^[A-Za-z_][A-Za-z0-9_]*$" : {
                "type" : "object",
                "additionalProperties" : false,
                "properties": {
                  "Enabled" : {
                    "type" : "boolean",
                    "default" : false
                  },
                  "Permissions" : {
                    "type" : "string",
                    "enum": [ "ro", "wo", "rw"],
                    "default" : "ro"
                  },
                  "IPAddressGroups" : {
                    "type" : "array",
                    "items": {
                      "type" : "string"
                    },
                    "default" : [ "_localnet"]
                  },
                  "Paths" : {
                    "type" : "array",
                    "items": {
                      "type" : "string"
                    },
                    "default" : []
                  }
                }
              }
            }
          },
          "Style" : {
            "description": "TODO(mfl): Think this can be removed",
            "type" : "string"
          },
          "Notifications" : {
                "type" : "object",
                "patternProperties": {
                  "^[A-Za-z_][A-Za-z0-9_]*$" : {
                    "type" : "object",
                    "additionalProperties" : false,
                    "properties": {
                      "Prefix" : {
                        "type" : "string"
                      },
                      "Suffix" : {
                        "type" : "string"
                      },
                      "Events" : {
                        "type" : "array",
                        "default" : [ "create" ],
                        "items" : {
                          "type" : "string",
                          "enum": [ "create", "delete", "restore", "reducedredundancy"]
                        }
                      }
                    }
                  }
            },
            "additionalProperties": false
          },
          "additionalProperties" : false
        }
      },

      "template" : {
        "type" : "object",

        "properties": {
          "Instances" : { "$ref": "#/definitions/instances" },
          "DeploymentUnits" : { "$ref" : "#/definitions/deployment-units" },
          "RootFile" : {
            "type" : "string",
            "description": "The name of the root template file in the build aretefact"
          },
          "Fragment" : {
            "type" : "string"
          },
          "Parameters" : {
            "type" : "object",
            "patternProperties": {
              "^[A-Za-z_][A-Za-z0-9_]*$" : {
                "additionalProperties" : false,
                "type" : "object",
                "properties": {
                  "Key" : {
                    "type" : "string"
                  },
                  "Value" : {
                    "type" : "string"
                  }
                },

                "required": [ "Key "]
              }
            }
          },
          "Attributes" : {
            "type" : "object",
            "patternProperties" : {
              "^[A-Za-z_][A-Za-z0-9_]*$" : {
                "additionalProperties" : false,
                "type" : "object",
                "properties" : {
                  "TemplateOutputKey" : {
                    "description": "The name of the template output you want to map to an attribte",
                    "type" : "string"
                  },
                  "AttributeType" : {
                    "description": "The output type to map the attribute with",
                    "enum": [ "dns", "arn", "url", "name", "ipaddress", "key", "port", "username", "password", "region"],
                    "type" : "string"
                  }
                },

                "required" : [ "TemplateOutputKey", "AttributeType" ]
              }
            }
          },
          "NetworkAccess" : {
            "type" : "boolean",
            "default" : false
          }
        },
        "additionalProperties": false,

        "required": [ "RootFile"]
      }

    },

    "type": "object",

    "patternProperties": {
      "^[A-Za-z0-9_-]*$" : {
        "properties": {
          "s3" : { "$ref" : "#/definitions/s3"},
          "template" : { "$ref" : "#/definitions/template"}
        },
        "additionalProperties": true
      }
    },

    "additionalProperties" : false
}
```

For examples of existing implementations of the multi-language code blocks, please see:
- [existing reference page](https://hamlet.io/docs/reference/component-reference)
- [docs markdown](https://raw.githubusercontent.com/hamlet-io/docs/master/docs/reference/component-reference.md)

**Comment by RossMurr4y** [comment]
Updated ticket with @roleyfoley's schema definition [here](https://hamlet-docs-git-add-schema-documents.hamlet.now.sh/schema/latest/blueprint/component.json).

**Comment by roleyfoley** [comment]
I think we can call this done and move future changes to new tickets

**Comment by RossMurr4y** [comment]
Agreedamundo.
