### ISSUE TITLE
Feature - Document hamlet docker image tags

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#17]
Currently the dockerhub repository and the hamlet-io/docker-hamlet repositories contain the definitions for each of the docker image tags. As the developer guides recommend using the docker containers instead of installations from source, the developer guides should become the central location for this documentation, and the hamlet-docker repo README updated to direct users to the developer guide instead.

This should coincide with the docker image restructure in hamlet-io/docker-hamlet#21

**Comment by roleyfoley** [comment]
Not sure if the developer guide is quite the right spot for this. The docker images are also used by users of hamlet, for manual deployments and CI/CD integration

**Comment by RossMurr4y** [comment]
There seems to be a lot of content where we start out writing the docs with contributors in mind but there's overlap with hamlet users. Ideally such content is something that users encounter early on but not within the Getting Started Guide (too long). I'm not really excited about adding more top-level headings to the docs so in the current structure that would mean it needs to go somewhere in Tutorials.

Additionally, outside of the create/deploy/upgrade/automate tutorial headings we need a place to explain the life cycle of a hamlet controlled account/product. I think that's a really critical piece of the puzzle.

So - without making it sound like we need a tonne of new tutorials, i think we need something that is the launching-point for them - basically the "start here to get yourself setup and understand the why, before we teach you the how".

This section could cover off:

- Most of the "setting up a local workspace" content from #16 
- consolidated with container explanations from #17 (this pr)
- Release schedule/calendar content from #8 #9 #10 

```text
tutorials
└── Starting_Out
    ├── Hamlet_Lifecycle
    └── Your_Product_Lifecycle
```
Something like this?
