### ISSUE TITLE
Update Algolia Search Configuration

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#2]
hamlet-docs is configured to use Algolia DocSearch for its search functionality. The original site was configured under a different repository and so the DocSearch web crawler is now looking at old/non-existent content.

In order to fix this, we need to submit a PR on the docsearch-configs repository, updating our own configuration. This cannot be done until we have our production domain in place.

https://github.com/algolia/docsearch-configs/blob/master/configs/hamlet.json

```json
{
  "index_name": "hamlet",
  "start_urls": [
    "https://hamlet.io/docs/",
    "https://hamlet.io/docs/index"
  ],
  "sitemap_urls": [
    "https://hamlet.io/sitemap.xml"
  ],
  "sitemap_alternate_links": true,
  "stop_urls": [],
  "selectors": {
    "lvl0": {
      "selector": ".menu__link--sublist.menu__link--active",
      "global": true,
      "default_value": "Documentation"
    },
    "lvl1": "[class^='docItemContainer_'] h1",
    "lvl2": "[class^='docItemContainer_'] h2",
    "lvl3": "[class^='docItemContainer_'] h3",
    "lvl4": "[class^='docItemContainer_'] h4",
    "lvl5": "[class^='docItemContainer_'] h5",
    "text": "[class^='docItemContainer_'] p, [class^='docItemContainer_'] li"
  },
  "selectors_exclude": [
    ".hash-link"
  ],
  "conversation_id": [
    "1093114637"
  ],
  "nb_hits": 3368
}
```

**Comment by ml019** [comment]
@RossMurr4y Domain is now under our control. Let me know what DNS record you need and I'll add it.

**Comment by ml019** [comment]
Also, do we want to move the docs repo to our new github org before updating the record?

**Comment by RossMurr4y** [comment]
Absolutely. Is the org ready to go?

**Comment by RossMurr4y** [comment]
Now we've migrated the docs to the new org, i have submitted a PR for this:
https://github.com/algolia/docsearch-configs/pull/1779

**Comment by RossMurr4y** [comment]
PR is now merged and our production site should be getting scraped/indexed regularly.
