### ISSUE TITLE
Discussion - Tutorial Groups

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#31]
## Description

When I drafted the skeleton of the documentation site I wanted the tutorial headings to be really clear on the lifecycle of a product with hamlet. I settled on "Create", "Deploy", "Upgrade" and "Automate" because I felt they made it very clear what hamlet could do and also how a user might progress through them.

The idea is sensible but I feel we could gain more from aligning the tutorials with the top level CLI commands that are available (currently "Create", "Generate", "Manage", "Query", "Run" and "Test". It would make the documentation and the CLI more cohesive as well as make things pretty clear as to where to find documentation (and quite clear on where to put said documentation also).

I would like to discuss here whether this change makes sense for the documentation and confirm we remain happy with these CLI commands as they are. Also if there are more of these in the near future (@roleyfoley and I have discussed a "Validate" for validating a CMDB) then this would be a good time to discuss.

**Comment by roleyfoley** [comment]
Closing based on current structure and will revisit if it comes back up
