### ISSUE TITLE
Feature Request - CMDB Schemas

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#5]
The CMDB [schemas](https://hamlet.io/docs/reference/cmdb/cmdb-folder-structure-02) have already been defined with examples, however we should also include full reference schemas so CMDB authoring/maintaining is as simple as possible. 

Tab elements have already been created with places for the schemas, they just need to be updated from their placeholders.

This issue will be considered completed when the following cmdb files have schemas:

- [ ]  solution.json
- [ ]  segment.json
- [ ]  build.json
- [ ]  settings.json
- [ ]  credentials.json
- [ ]  template.json
- [ ]  stack.json
- [ ]  domains.json
- [ ] tenant.json
- [ ] ipaddressgroups.json
- [ ] countrygroups.json
- [ ] account.json
- [ ] deployment_unit.json
- [ ] <resource>.json

**Comment by roleyfoley** [comment]
Might need to review how we generate schemas I don't think we can generate one for each file since each file can actually have the full schema in it

**Comment by roleyfoley** [comment]
@RossMurr4y Can you please review

**Comment by RossMurr4y** [comment]
https://github.com/hamlet-io/engine/issues/1491 will enable schema references within the composite object structure. 
This will mean that having true references between schemas will also be possible.
Rather than having one schema per file as originally requested here, https://github.com/hamlet-io/engine/issues/1477 proposes schema per composite object which is far more maintainable. Together, these two tickets will accomplish the intention of this ticket.
Closing.
