### ISSUE TITLE
Fix - Empty Reference Data Arrays

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#56]
## Missing or Incorrect Documentation

The reference data tables that parse Hamlet JSONSchema and display it for human consumption display some empty and redundant tables.

## Issue Checklist
- [x] Added Issue to the `hamlet roadmap` project.
- [x] Assigned the appropriate Issue labels.

**Comment by roleyfoley** [comment]
Fixed as part of schema refactoring
