### ISSUE TITLE
Fix - Reference Data to handle Ref Values

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#61]
## Description

JSONSchema documentation tables and examples should be updated to handle `{ "$ref" : "#my.reference.target"}` values. They currently show up as `<undefined>` in the examples. In the tables they should be links to the target schema.

![image](https://user-images.githubusercontent.com/20530524/94878294-48f18b80-04a0-11eb-9444-8560508b38ff.png)

## Issue Checklist
- [ ] Added Issue to the `hamlet roadmap` project.
- [ ] Assigned the appropriate Issue labels.

**Comment by roleyfoley** [comment]
@RossMurr4y please review
