### ISSUE TITLE
Migrate Github Projects from COT

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#7]
Existing github projects that are to serve as the roadmaps for hamlet remain under codeontap org. These should be either migrated or recreated under the hamlet-io org, and the docs roadmap link should be updated to send to the correct org projects board.

- [ ] Create/Migrate the codeontap + plugin projects from codeontap > hamlet-io orgs
- [ ] Update docs site [navbar link](https://v2.docusaurus.io/docs/theme-classic/#navbar-links) to point to the hamlet-io roadmaps

**Comment by ml019** [comment]
Was thinking about this and whether we 
1. use the change of name as an opportunity to remove a lot of the deprecated stuff in gen3 so hamlet gets a clean start
2. Carry gen3 over as is - that way we keep the commit history and older versions.

I'm leaning towards 2.

**Comment by RossMurr4y** [comment]
if we went with #1, I would also recommend that at the same time that AWS is extracted from gen3 (would become just 'gen' now right?) and made into its own provider plugin.

I like that option, but I think realistically it'll come down to how long that process (removing deprecated items + AWS extraction) will take.

**Comment by roleyfoley** [comment]
@ml019  Are you talking about removing the deprecated repos rather than specific items inside the repos? 
If that's the case we could just transfer them over from org to org. I'd like to rename gen3 to engine though if we can.

**Comment by RossMurr4y** [comment]
> I'd like to rename gen3 to engine though if we can. :+1: 

I did the migration and rename with the docs site so its quite straightforward to do.

**Comment by ml019** [comment]
@roleyfoley I'm actually talking about TODOs in the engine which are there for bckwards compatability.

I think we've agreed we are moving the repos across so I think we leave all this stuff in there and deal with it as part of the normal release strategy.

**Comment by RossMurr4y** [comment]
Closing - migration has been completed and a new project structure agreed upon here: https://github.com/orgs/hamlet-io/projects/4
