### ISSUE TITLE
Bug - Missing Attribute Schemas

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#76]
## Missing or Incorrect Documentation
Some reference data that should result in its own datatable is not displaying its own table configuration - only the parent heading.
An example of this is the `DataFeed` component schema at `DataFeed.Bucket.Include.Order` - it is displaying in the JSON example but there is no table displaying the "include" object structure. This is likely an issue with the implementation of recursion over the attribute structure.

## Issue Checklist
- [x] Added Issue to the `hamlet roadmap` project.
- [x] Assigned the appropriate Issue labels.

**Comment by RossMurr4y** [comment]
Though the data tables have been recently overhauled, this issue remains.  The JSONSchema however appears correct, so this is definitely an issue in the docs site, not the Hamlet Deploy engine.

Visible here:https://docs.hamlet.io/reference?type=component&instance=datafeed
Schema here: https://github.com/hamlet-io/docs/blob/master/static/schema/latest/blueprint/schema-component-datafeed-schema.json

**Comment by roleyfoley** [comment]
Done
