### ISSUE TITLE
Move site to docs.hamlet.io

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/docs#89]
This ticket is to move this website from its current home at `https://hamlet.io` over to https://docs.hamlet.io`. This will allow us to develop a basic closed site at hamlet.io which will be used for product promotion and sales of hamlet services  

This site will become the documentation site for the hamlet services with a primary focus on the hamlet deploy tool initially 

## Target Audience
- [X] hamlet users
- [X] hamlet framework developers (incl. plugins)

**Comment by ken9ross** [comment]
Implemented with PR#88
