### ISSUE TITLE
[BUG] Schema generation Github Action Failing

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/docs#93]
## Description
After merging the schema instance changes in #90 the github action which updates the schema pages seems to be failing 

See https://github.com/hamlet-io/docs/runs/1867667325?check_suite_focus=true

**Comment by RossMurr4y** [comment]
Updates to the Github Action have been published under the previous tag ("v1"). Re-running the workflows have resulted in a success.

Closing.
